// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yozeawddmurlpwvxxetc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvemVhd2RkbXVybHB3dnh4ZXRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3Mjg1MDEsImV4cCI6MjA3MDMwNDUwMX0.-PtizE1Z4WdpUnoRzuMWTkzdACcn28bKh92z--NtI6o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});