// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zojtwgycwtwnqwhzynqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvanR3Z3ljd3R3bnF3aHp5bnFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUzMzE1MjIsImV4cCI6MjA1MDkwNzUyMn0.QpP8oQTeY5DK8PcN9qAu5lOLdwe4ci2NrXSUjaLKiuY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);